sudo: false
language: node_js
node_js:
- 'lts/*'
env:
  global:
  - secure: L8B2bdVyjwNCMZbxlYs8Dw7W3yB6D9vgy+iRbCMCfzUvXMu/XydMc2OO4S+uXVL2CpV4n1LUplU6ab4Yz7Mcudh5zIvBPeycXCXlgoPg+tCszG+8UNTqyjYJMJnUr+OAzw8g2Kd2ri/stT1Qmhtyw57BF4pH2MT6i2KJc3xgUMbjYef3BTgdRG4pJcdiG3YLbzX+VLPSRBxNXVL9dkXJVFRhZ/pYAOXDegTUzYMrOjyiX9nU8rRCFRNFtEKregYZ3Jmy9eJEM2JxzY/vBbbADw84wf3XIilpCPw+7DHc05iMkKhOEuwBxWbjX0i5IwqbzN4Dgj2fOoCvFVkimvI79co+rFYdR4Tstmg1h582fodEUOHafWzDQ1SRyl1LH5uL0rj8eyXDbHFbnLqJmm5x/M51gTU2aTW/BJo73IkK255M24R+LO1OtXLR9dz+VQF5yaHQGsN0He3ggfI++1WvphkMAq/AJUso8+DAWjpkxYxqcLhpM0rL+fK5QSTPyhgl0rNafQuZHJDmu88ssKtsTa5mDLQYxM2xTTgTQRjDYIwhtYxs/KR666x6SH0uHDH5hWHHGfjfeqkDkbWyoUCVKKEAM6vYRT3eWQ8DFlz79361kfSVJ3xIq/szIjND7JS5O3eF4ju7xgm1q1oZrTLf5817jqs5nwkc147sRApJQ60=

after_success:
# update gh-page only for master and not pull requests
- if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    chmod +x ./resources/scripts/update-gh-pages.sh; "./resources/scripts/update-gh-pages.sh";
  else echo "Not deploying artifacts for $TRAVIS_BRANCH"; fi
